{% set version = "1.11.3" %}
{% set hash = "2e885b3ca2666398ebfd136d000ab86a07244967da736227f5e42723ac10b50a0bbaa18ccad48961b8dbbd2cb14b6e5d068177c37287d71ebcd5e3ead8a9a98b" %}
{% set name = "avrocpp" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: avro-cpp-{{ version }}.tar.gz
  url: https://archive.apache.org/dist/avro/avro-{{ version }}/cpp/avro-cpp-{{ version }}.tar.gz
  sha512: {{ hash }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - pkg-config      # [osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - snappy
    - xz
    - zlib
    - boost
    - msinttypes      # [win]
  run:
    - xz
    - snappy
    - zlib
    - boost

test:
  commands:
    - test -f ${PREFIX}/lib/libavrocpp_s.a  # [unix]
    - conda inspect objects {{ name }}      # [osx]
    - conda inspect linkages {{ name }}     # [linux]

about:
  home: http://hadoop.apache.org/avro
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Avro is a serialization and RPC framework.'


extra:
  recipe-maintainers:
    - mariusvniekerk
