{% set version = "1.11.3" %}
{% set name = "avrocpp" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: release-{{ version }}.tar.gz
    url: https://github.com/apache/avro/archive/release-{{ version }}.tar.gz
    sha256: da377ac1cf8b91458bf702cbcfb214eecb5c399b267f0ca9c0aade6cabaf126e
    patches:
        - patches/0001-Make-constinit-a-reserved-word.patch

build:
    number: 0
    skip: true  # [win and vc<14]

requirements:
    build:
        - ninja
        - cmake
        - pkg-config  # [osx]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - snappy
        - xz
        - zlib
        - libboost-devel
        - msinttypes  # [win]

test:
    commands:
        - test -f ${PREFIX}/lib/libavrocpp_s.a      # [unix]
        - test -f ${PREFIX}/lib/libavrocpp.so       # [unix]
        - test -f ${PREFIX}/include/avro/Types.hh   # [unix]
        - if not exist %PREFIX%\\Library\\include\\avro\\Types.hh exit 1  # [win]

about:
  home: https://avro.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Avro is a serialization and RPC framework.'


extra:
  recipe-maintainers:
    - apmorton
    - mariusvniekerk
