{% set version = "1.11.3" %}
{% set hash = "fba242aef77ec819d07561fcba93751721956de8d0cae8e1f2f300b54b331bae" %}
{% set name = "avrocpp" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://archive.apache.org/dist/avro/avro-{{ version }}/cpp/avro-cpp-{{ version }}.tar.gz
    sha256: {{ hash }}
  - path: ../src/FindSnappy.cmake
  - path: ../src/msstdint.h
    folder: api/

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make
    - pkg-config      # [osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - snappy
    - xz
    - zlib
    - libboost-devel
    - msinttypes      # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libavrocpp_s.a  # [unix]
    - conda inspect objects {{ name }}      # [osx]
    - conda inspect linkages {{ name }}     # [linux]

about:
  home: http://hadoop.apache.org/avro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Avro is a serialization and RPC framework.'


extra:
  recipe-maintainers:
    - mariusvniekerk
