{% set version = "1.8.2" %}
{% set hash = "c17d84613187dda3611c9c95d6f3388036a330ba" %}
{% set name = "avrocpp" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: avro-cpp-{{ version }}.tar.gz
    url: https://archive.apache.org/dist/avro/avro-{{ version }}/cpp/avro-cpp-{{ version }}.tar.gz
    sha1: {{ hash }}

build:
    number: 1
    skip: true  # [win and vc<14]

requirements:
    build:
        - cmake
        - pkg-config  # [osx]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - snappy
        - xz
        - zlib
        - boost
        - msinttypes  # [win]
    run:
        - xz
        - snappy
        - zlib
        - boost

test:
    commands:
        - test -f ${PREFIX}/lib/libavrocpp_s.a  # [unix]

about:
  home: http://hadoop.apache.org/avro
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Avro is a serialization and RPC framework.'


extra:
  recipe-maintainers:
    - mariusvniekerk
