travis:
  secure:
    BINSTAR_TOKEN: s+xkPtOYu0zJU5ox+pZ/HpqSgWFb4oEZzjIKZC9+BUj2h1D3I9KyI03oVLzYbNRu419QKnRBzveI4suTPBT3CG6oKyq4ROfu2JXzrHa8gQH9YEMypBHG/o9mfJYfV7oAtSnx/UlGvJItGWnCaXDAXHzmc3L7/xeySaWChszs7A/WBkuy25QKY1pnFpPZ5eil650oSvVTtHL2qWxCO8tgE5RYmeODNItSnZvVeX4SdC+55229PEBExpBBcR18f9REcezlbFR8RgwbqmvKx9mSS3nYXlqqy/p7FWx9px9fK2Ew8uj03qGJ43xbNfCmvx5UT+tWYwWa9Kxlw7K/rsCesAaKo8Z+a8k4fAK+Zw+l33hvPPBb/95mPKAKCw1A1F18Fye7lLTv3qY4ygXNmRh5zy9/lTGFw9iFqjqwD6NfW99/VObFEtSwTezcbBcM9zf5rXYHwq38Ok6sYWFfQRZP97eHjpI9tn1N0QcwtrjZTgpK6gzIWrzKoX2iwvll4ToiqR+JkoAEB3ketAGFOD3gkyNLTK/E1WgSTRIeJJrsl4gtEbKsct4GF50gRBKALfKRfJ6MjOTbaegRe699P0XJPTNglh7VuXOj2m1LuIxooAiZconseDtobXCjeG6ZUwA/PRR4tZFiU3RvrsGXzeZ3F/3tCUFM2k4dzS7vZd+URI0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
